name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/haven_kim.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico/Pacifico-Regular.ttf
    - family: Source_Sans_Pro
      fonts:
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Italic.ttf
          style: italic